'''
Django settings for MLOP project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
'''

from pathlib import Path
import os
import logging
from django.core.exceptions import DisallowedHost
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-m+plryv=d(5#e1ol#k#o-%jo5=m5hvdy3pqv&n)h0_1skn3e2+'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback-secret-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'joycedevresource-ddg5hrgbafaccaf6.centralus-01.azurewebsites.net',
    '.azurewebsites.net',
    'localhost',
    '127.0.0.1',
    '169.254.129.3',
    '169.254.129.4',
    '*',
]

class IgnoreAzureDisallowedHost(logging.Filter):
    def filter(self, record):
        if '169.254.' in str(record.msg):
            return False
        return True

logging.getLogger('django.security.DisallowedHost').addFilter(IgnoreAzureDisallowedHost())
# ALLOWED_HOSTS += [f'169.254.{i}.{j}' for i in range(256) for j in range(256)]
# Allow all Azure health check internal IPs (169.254.0.0/16)

# Safe Azure health check bypass
# if os.environ.get('AZURE_HEALTH_CHECK') == 'true':
#     # Only allow '*' for requests from Azure health checks
#     # This will not affect normal external traffic because health checks
#     # hit internal IPs (169.254.*.*)
#     HEALTH_CHECK_ALLOWED_HOSTS = ['*']

# class HealthCheckHostMiddleware:
#     def __init__(self, get_response):
#         self.get_response = get_response

#     def __call__(self, request):
#         host = request.get_host()
#         if host.startswith('169.254.'):
#             request.get_host = lambda: 'joycedevresource-ddg5hrgbafaccaf6.centralus-01.azurewebsites.net'
#         return self.get_response(request)

# MIDDLEWARE = ['MLOP.settings.HealthCheckHostMiddleware'] + MIDDLEWARE
#     # Insert the middleware at the top (before CommonMiddleware)
#     MIDDLEWARE = ['MLOP.settings.HealthCheckHostMiddleware'] + MIDDLEWARE

CSRF_TRUSTED_ORIGINS = [
    'https://*.azurewebsites.net',
    'https://joycedevresource-ddg5hrgbafaccaf6.centralus-01.azurewebsites.net',
    # 'https://unretaliated-oversweetly-loren.ngrok-free.dev',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'store',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MLOP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MLOP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'https://joycedevresource-ddg5hrgbafaccaf6.centralus-01.azurewebsites.net',
    # 'https://unretaliated-oversweetly-loren.ngrok-free.dev',
]
CORS_ALLOW_CREDENTIALS = True

# Security settings
# HTTPS / HSTS
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600  # start with 1 hour, increase gradually
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Secure cookies
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# XSS & content type protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Logging to ignore DisallowedHost spam from Azure health checks
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'level': 'INFO'},
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}